USE credit_scoring;

CREATE TABLE credit_defaults (
ID INT AUTO_INCREMENT PRIMARY KEY,
LIMIT_BAL DECIMAL(10,2),
SEX TINYINT,
EDUCATION TINYINT,
MARRIAGE TINYINT,
AGE INT,
PAY_0 TINYINT,
PAY_2 TINYINT,
PAY_3 TINYINT,
PAY_4 TINYINT,
PAY_5 TINYINT,
PAY_6 TINYINT,
BILL_AMT1 DECIMAL(10,2),
BILL_AMT2 DECIMAL(10,2),
BILL_AMT3 DECIMAL(10,2),
BILL_AMT4 DECIMAL(10,2),
BILL_AMT5 DECIMAL(10,2),
BILL_AMT6 DECIMAL(10,2),
PAY_AMT1 DECIMAL(10,2),
PAY_AMT2 DECIMAL(10,2),
PAY_AMT3 DECIMAL(10,2),
PAY_AMT4 DECIMAL(10,2),
PAY_AMT5 DECIMAL(10,2),
PAY_AMT6 DECIMAL(10,2),
default_payment_next_month TINYINT
);